### ISSUE TITLE
How do I install this project in Windows

### ISSUE THREAD

**Issue by zhanghongyong123456** [zerollzeng/tensorrt-zoo#40]
want to compile under Windows, but I am not familiar with Cmake. Could you briefly explain the compile process and how to configure Cmake? Thank you，windows10.1  python 3.8  cuda 10.2 TensorRT  7.2.1.6  opencv 4.5.1  cmake GUI  3.19.2  

thank you very much for your help

**Comment by zhanghongyong123456** [comment]
> want to compile under Windows, but I am not familiar with Cmake. Could you briefly explain the compile process and how to configure Cmake? Thank you，windows10.1 python 3.8 cuda 10.2 TensorRT 7.2.1.6 opencv 4.5.1 cmake GUI 3.19.2
> 
> thank you very much for your help

I got this problem at compile time
![31](https://user-images.githubusercontent.com/48466610/126941828-02ec2e0a-6a72-4981-b7b2-2c923c1275ed.png)
When I remove the -d identifier
![32](https://user-images.githubusercontent.com/48466610/126941904-18d8f7e5-da8b-4cd0-8ec4-90a489622d4d.png)
![33](https://user-images.githubusercontent.com/48466610/126941931-c974c9ba-1b39-42c5-a12e-a0e19ee9a248.png)

**Comment by zerollzeng** [comment]
Sry I don't familiar with windows platform so can not help you with this :(

**Comment by drostifrosti** [comment]
you pass CMake variables with `-D<var>=<value>` without a space between `D` and `<`, that's why I suggested to read a tutorial beforehand.
If you're on Windows, why don't you use the more comfortable GUI to configure the variables?
Regarding the errors: you can use my forks of @zerollzeng repos (which exclude parts of his work, which I didn't need in my personal project)

**Comment by zhanghongyong123456** [comment]
> you pass CMake variables with `-D<var>=<value>` without a space between `D` and `<`, that's why I suggested to read a tutorial beforehand.
> If you're on Windows, why don't you use the more comfortable GUI to configure the variables?
> Regarding the errors: you can use my forks of @zerollzeng repos (which exclude parts of his work, which I didn't need in my personal project)
I find that your personal innovation pool is no different from this one,I have solved -d. I don't know how to set parameters for the second problem. I hope you can give me some advice
https://github.com/drostifrosti/tensorrt-zoo

**Comment by zhanghongyong123456** [comment]
> Sry I don't familiar with windows platform so can not help you with this :(

ok，thank you for  your reply， I've been consulting with the other bigwigs

**Comment by zhanghongyong123456** [comment]
> you pass CMake variables with `-D<var>=<value>` without a space between `D` and `<`, that's why I suggested to read a tutorial beforehand.
> If you're on Windows, why don't you use the more comfortable GUI to configure the variables?
> Regarding the errors: you can use my forks of @zerollzeng repos (which exclude parts of his work, which I didn't need in my personal project)

i use  yours progect  compiler，get this error，Do I lack a Boost library or do I need to compile it separately，I hope to receive your prompt reply
![image](https://user-images.githubusercontent.com/48466610/127100456-69bc5dda-219b-434d-a24c-b5402e639249.png)

**Comment by zhanghongyong123456** [comment]
> you pass CMake variables with `-D<var>=<value>` without a space between `D` and `<`, that's why I suggested to read a tutorial beforehand.
> If you're on Windows, why don't you use the more comfortable GUI to configure the variables?
> Regarding the errors: you can use my forks of @zerollzeng repos (which exclude parts of his work, which I didn't need in my personal project)
When I was using your library to install，I also have Boost1.76 installed
![image](https://user-images.githubusercontent.com/48466610/127105245-b5439ad6-60dc-49a6-a65f-47eddb2065cb.png)

**Comment by drostifrosti** [comment]
> I find that your personal innovation pool is no different from this one <

I can assure you, I got it to work under Windows with these changes.
You have to point the variable CUDART to the path of the cudart.lib library

PS: can you please exclude your answer from the quote block

**Comment by zhanghongyong123456** [comment]
> > I find that your personal innovation pool is no different from this one <
> 
> I can assure you, I got it to work under Windows with these changes.
> You have to point the variable CUDART to the path of the cudart.lib library
> 
> PS: can you please exclude your answer from the quote block

Hello I use Cmake GUI configuration.I have respecified your path, and I have installed boost1.76 version. I want to know how your cmake is configured, could you please tell me
![image](https://user-images.githubusercontent.com/48466610/127114040-848c7928-0c1a-46a9-8d50-7c5b465a5701.png)
Thank you very much for your reply

**Comment by zhanghongyong123456** [comment]
> > I find that your personal innovation pool is no different from this one <
> 
> I can assure you, I got it to work under Windows with these changes.
> You have to point the variable CUDART to the path of the cudart.lib library
> 
> PS: can you please exclude your answer from the quote block
I'm sorry, I was wondering which one that was,
PS: can you please exclude your answer from the quote block

**Comment by drostifrosti** [comment]
There is no shortcut to configure the CMake script, I've got local paths in my CMake configuration which are of no help to you.
You're on the right track, just keep going.

**Comment by zhanghongyong123456** [comment]
> There is no shortcut to configure the CMake script, I've got local paths in my CMake configuration which are of no help to you.
> You're on the right track, just keep going.

Now I don't know which parameters need to be configured. The main reason is to know which parameters you have configured, and I can easily find my own path according to your configuration，Looking forward to your reply

**Comment by drostifrosti** [comment]
for tensorrt-zoo:
> BUILD_PYTHON OFF
> BUILD_TEST OFF
> ENABLE_PRELU_FP16 ON
> SM_VERSION 86
> TENSORRT_INCLUDE_DIR `<local path>`\TensorRT-7.2.2.3\include
> TENSORRT_ROOT `<local path>`\TensorRT-7.2.2.3
> OpenCV_DIR `<local path>`\OpenCV_4.5.1\install\x64\vc16\lib

**Comment by zhanghongyong123456** [comment]
> OpenCV_DIR

yes，I configured all of that, but for how to configure the subdirectory cmakelist.txt（openpose）
![image](https://user-images.githubusercontent.com/48466610/127122030-75396154-8c5f-43ab-b024-af168bffdc14.png)
I'm not sure that's right

**Comment by zhanghongyong123456** [comment]
> > OpenCV_DIR
> 
> yes，I configured all of that, but for how to configure the subdirectory cmakelist.txt（openpose）
> ![image](https://user-images.githubusercontent.com/48466610/127122030-75396154-8c5f-43ab-b024-af168bffdc14.png)
> I'm not sure that's right
Because when I cmake configure, I get this message
![image](https://user-images.githubusercontent.com/48466610/127122302-361a90cc-00d2-41b1-b311-9811ae1fcd22.png)

**Comment by drostifrosti** [comment]
maybe your CMake version 3.19.2 is too old for this Boost version and preemptively throws this warning, I've got 1.75 and 3.20.4 and no warning
no severe issue, more or less a note

**Comment by zhanghongyong123456** [comment]
> maybe your CMake version 3.19.2 is too old for this Boost version and preemptively throws this warning, I've got 1.75 and 3.20.4 and no warning
> no severe issue, more or less a note

Can I ignore this warning, then I can use VS 2019 directly ALL BUILD and INSTALL, or I can use cmake directly BUILD

**Comment by drostifrosti** [comment]
you can ignore this warning
you just build the project in VS2019 directly or via ALL_BUILD
> or I can use cmake directly BUILD

?

**Comment by zhanghongyong123456** [comment]
> you can ignore this warning
> you just build the project in VS2019 directly or via ALL_BUILD
> 
> > or I can use cmake directly BUILD
> 
> ?
I used this command when compiling and installing the Opencv GPU，
cmake  --build  "E:\opencvgpu\build6" --target INSTALL  --config Release

**Comment by zhanghongyong123456** [comment]
> you can ignore this warning
> you just build the project in VS2019 directly or via ALL_BUILD
> 
> > or I can use cmake directly BUILD
> 
> ?

According to your suggestion, I updated cmake 3.21.1 without that warning. However, this error occurs when I use VS2019 Release 64 ALL BUILD. What should I do
![40](https://user-images.githubusercontent.com/48466610/127252843-76c2ca53-4156-4d2c-ae02-f4ef79e0e944.png)
![41](https://user-images.githubusercontent.com/48466610/127252851-dfdb4f76-6ba0-4801-8abc-fdcc3a845c65.png)
![42](https://user-images.githubusercontent.com/48466610/127252861-56febecb-6bc6-4b40-a613-54aac87517c2.png)

**Comment by zhanghongyong123456** [comment]
> 您可以忽略此警告，
> 您只需直接或通过 ALL_BUILD 在 VS2019 中构建项目
> 
> > 或者我可以直接使用 cmake 构建
> 
> ?
I want to know which file this needs to be commented in
![image](https://user-images.githubusercontent.com/48466610/127272934-1f9f8c63-0b63-4f5f-95b8-c3d8e323adad.png)

**Comment by drostifrosti** [comment]
already fixed here: https://github.com/drostifrosti/tiny-tensorrt/commit/b092efb7dad578c989257794ae3663e704e6f7bc

**Comment by drostifrosti** [comment]
> > 您可以忽略此警告，
> > 您只需直接或通过 ALL_BUILD 在 VS2019 中构建项目
> > > 或者我可以直接使用 cmake 构建
> > 
> > 
> > ?
> > I want to know which file this needs to be commented in
> >

don't quite understand what you're asking for, maybe have a look here: https://github.com/drostifrosti/tiny-tensorrt/commit/cd7cda9598c3f6b7473de09ed9709975a759a8c7

**Comment by zhanghongyong123456** [comment]
> > > 您可以忽略此警告，
> > > 您只需直接或通过 ALL_BUILD 在 VS2019 中构建项目
> > > > 或者我可以直接使用 cmake 构建
> > > 
> > > 
> > > ?
> > > I want to know which file this needs to be commented in
> 
> don't quite understand what you're asking for, maybe have a look here: [drostifrosti/tiny-tensorrt@cd7cda9](https://github.com/drostifrosti/tiny-tensorrt/commit/cd7cda9598c3f6b7473de09ed9709975a759a8c7)

I updated cmake3.21.1 using your project file,Still failed to compile,This is the result of compilation. I don't know what to do
[output.txt](https://github.com/zerollzeng/tensorrt-zoo/files/6890793/output.txt)

**Comment by drostifrosti** [comment]
Please mark the error lines, I'm not searching through 32k lines of output

**Comment by zhanghongyong123456** [comment]
> Please mark the error lines, I'm not searching through 32k lines of output

i am sorry，i run find out

**Comment by zhanghongyong123456** [comment]
> Please mark the error lines, I'm not searching through 32k lines of output
I can't seem to find the file. I still have this problem when I copy the file I downloaded from the OpenPose distribution
![image](https://user-images.githubusercontent.com/48466610/127276795-90cdf904-437b-4a47-b653-56c1032e1d00.png)

**Comment by drostifrosti** [comment]
I wanted to compare the performance of tensorrt-zoo's OpenPose to the original OpenPose, you could comment out the orig. OpenPose part OR put the complete OpenPose distribution somewhere and add an include directory to testopenpose in the CMake

**Comment by zhanghongyong123456** [comment]
> I wanted to compare the performance of tensorrt-zoo's OpenPose to the original OpenPose, you could comment out the orig. OpenPose part OR put the complete OpenPose distribution somewhere and add an include directory to testopenpose in the CMake

ok，I have a try

**Comment by zhanghongyong123456** [comment]
> > I wanted to compare the performance of tensorrt-zoo's OpenPose to the original OpenPose, you could comment out the orig. OpenPose part OR put the complete OpenPose distribution somewhere and add an include directory to testopenpose in the CMake
> 
> ok，I have a try

I added this in the folder（F:\project\test02\tensorrt-zoo-master\openpose） cmakelists.txt, hope to point it out
![image](https://user-images.githubusercontent.com/48466610/127284783-b58a8ed9-3be8-426d-ba00-45b5e67f7bf7.png)

**Comment by zhanghongyong123456** [comment]
> I wanted to compare the performance of tensorrt-zoo's OpenPose to the original OpenPose, you could comment out the orig. OpenPose part OR put the complete OpenPose distribution somewhere and add an include directory to testopenpose in the CMake
Sorry to bother you again, could you please take a look at your configuration, I wrote this seems not quite right, still reported the same error

**Comment by drostifrosti** [comment]
Which "same error" ?

**Comment by zhanghongyong123456** [comment]
> Which "same error" ?
I wrote the wrong cmakelist.txt
![image](https://user-images.githubusercontent.com/48466610/127299477-76b235f8-de58-4f55-b484-4efa36d997a4.png)

**Comment by zhanghongyong123456** [comment]
> Which "same error" ?

What I added seems wrong. Could you please give me an example? I am looking forward to your prompt reply

**Comment by drostifrosti** [comment]
use `target_include_directories(testopenpose PRIVATE ".../include/openpose")`

**Comment by zhanghongyong123456** [comment]
> use `target_include_directories(testopenpose PRIVATE ".../include/openpose")`

it doesn't work，F:\project\test03\tensorrt-zoo-master\openpose\testopenpose.cpp(23,14): fatal error C1083: Cannot open include file: 'openpose/flags.hpp': No such file or directory，

I'm not going to do the comparison, but using the second method, could you tell me if I don't compare the Openpose source code with tensorrt, which code I should comment, hopefully for a hint，thank you

**Comment by zhanghongyong123456** [comment]
> use `target_include_directories(testopenpose PRIVATE ".../include/openpose")`

Big guy can add a friend to give directions, configure several days also can't succeed，It's breaking down  QQ 1037645638 ，Thank you so much

**Comment by drostifrosti** [comment]
> it doesn't work，F:\project\test03\tensorrt-zoo-master\openpose\testopenpose.cpp(23,14): fatal error C1083: Cannot open include file: 'openpose/flags.hpp': No such file or directory

you have to replace the ... with your specific path
look in the project properties in VS and check for include directories, which directory was included effectively

> Big guy can add a friend to give directions, configure several days also can't succeed，It's breaking down QQ 1037645638 ，Thank you so much

?

**Comment by zhanghongyong123456** [comment]
> > it doesn't work，F:\project\test03\tensorrt-zoo-master\openpose\testopenpose.cpp(23,14): fatal error C1083: Cannot open include file: 'openpose/flags.hpp': No such file or directory
> 
> you have to replace the ... with your specific path
> look in the project properties in VS and check for include directories, which directory was included effectively
> 
> > Big guy can add a friend to give directions, configure several days also can't succeed，It's breaking down QQ 1037645638 ，Thank you so much
> 
> ?
Do I need to configure it in VS after I have configured the GUI in CMAK，
![image](https://user-images.githubusercontent.com/48466610/127442261-02f93723-36ca-48ef-bb39-e2c48d9aaf97.png)
Hope to point out, the configuration of this has been four days, still did not succeed

**Comment by zhanghongyong123456** [comment]
> 采用 `target_include_directories(testopenpose PRIVATE ".../include/openpose")`
When I compile with cmake, there is only this error，Unable to find library without prompt，What to do about this error
![image](https://user-images.githubusercontent.com/48466610/127451926-6231143c-7f4b-495d-97e2-f6ff2ded27ed.png)

**Comment by drostifrosti** [comment]
You just check if the specified paths are correct in VS, but you don't have to post-configure anything in VS
> I'm not going to do the comparison, but using the second method, could you tell me if I don't compare the Openpose source code with tensorrt, which code I should comment, hopefully for a hint，thank you

Comment out the OpenPose includes `#include <openpose/flags.hpp>`, `#include <openpose/headers.hpp>` and the whole function `std::vector<std::vector<float>> openpose(int argc, char** argv)`

> When I compile with cmake, there is only this error，Unable to find library without prompt

You have to link against the nvcaffeparser.lib: https://github.com/drostifrosti/TensorRT

> Hope to point out, the configuration of this has been four days, still did not succeed

I needed 2 weeks to port the whole library stack to Windows and compare the 2 versions of OpenPose, so keep going ;-)

**Comment by zhanghongyong123456** [comment]
> > > it doesn't work，F:\project\test03\tensorrt-zoo-master\openpose\testopenpose.cpp(23,14): fatal error C1083: Cannot open include file: 'openpose/flags.hpp': No such file or directory
> > 
> > 
> > you have to replace the ... with your specific path
> > look in the project properties in VS and check for include directories, which directory was included effectively
> > > Big guy can add a friend to give directions, configure several days also can't succeed，It's breaking down QQ 1037645638 ，Thank you so much
> > 
> > 
> > ?
> > Do I need to configure it in VS after I have configured the GUI in CMAK，
> > ![image](https://user-images.githubusercontent.com/48466610/127442261-02f93723-36ca-48ef-bb39-e2c48d9aaf97.png)
> > Hope to point out, the configuration of this has been four days, still did not succeed
Hello, I would like to ask what I should do about this mistake. I am looking forward to your reply
![image](https://user-images.githubusercontent.com/48466610/127645639-981638c5-4072-4b44-8a69-6a46f1f7f33e.png)

**Comment by zhanghongyong123456** [comment]
> You just check if the specified paths are correct in VS, but you don't have to post-configure anything in VS
> 
> > I'm not going to do the comparison, but using the second method, could you tell me if I don't compare the Openpose source code with tensorrt, which code I should comment, hopefully for a hint，thank you
> 
> Comment out the OpenPose includes `#include <openpose/flags.hpp>`, `#include <openpose/headers.hpp>` and the whole function `std::vector<std::vector<float>> openpose(int argc, char** argv)`
> 
> > When I compile with cmake, there is only this error，Unable to find library without prompt
> 
> You have to link against the nvcaffeparser.lib: https://github.com/drostifrosti/TensorRT
> 
> > Hope to point out, the configuration of this has been four days, still did not succeed
> 
> I needed 2 weeks to port the whole library stack to Windows and compare the 2 versions of OpenPose, so keep going ;-)

Thank you for your encouragement

**Comment by zhanghongyong123456** [comment]
> You just check if the specified paths are correct in VS, but you don't have to post-configure anything in VS
> 
> > I'm not going to do the comparison, but using the second method, could you tell me if I don't compare the Openpose source code with tensorrt, which code I should comment, hopefully for a hint，thank you
> 
> Comment out the OpenPose includes `#include <openpose/flags.hpp>`, `#include <openpose/headers.hpp>` and the whole function `std::vector<std::vector<float>> openpose(int argc, char** argv)`
> 
> > When I compile with cmake, there is only this error，Unable to find library without prompt
> 
> You have to link against the nvcaffeparser.lib: https://github.com/drostifrosti/TensorRT
> 
> > Hope to point out, the configuration of this has been four days, still did not succeed
> 
> I needed 2 weeks to port the whole library stack to Windows and compare the 2 versions of OpenPose, so keep going ;-)

Sorry to bother you again. I commented the source Openpose (according to your advice) and compiled it again. I found that I didn't have what you said lib（nvcaffeparser.lib），Below is my Tensorrt directory
![image](https://user-images.githubusercontent.com/48466610/127964698-38ced279-18fb-4596-849d-99c81e1b7495.png)
this is CMakeLists.txt  about tensorrt  config, hope give me some advice,I'm not sure if my cmakelists.txt has a problem with the tensorrt modification or if the downloaded TensorRT is missing something(like you said nvcaffeparser.lib )
![image](https://user-images.githubusercontent.com/48466610/127965062-a163c59c-cde2-4251-9736-5b2345749b5c.png)

**Comment by zhanghongyong123456** [comment]
> > You just check if the specified paths are correct in VS, but you don't have to post-configure anything in VS
> > > I'm not going to do the comparison, but using the second method, could you tell me if I don't compare the Openpose source code with tensorrt, which code I should comment, hopefully for a hint，thank you
> > 
> > 
> > Comment out the OpenPose includes `#include <openpose/flags.hpp>`, `#include <openpose/headers.hpp>` and the whole function `std::vector<std::vector<float>> openpose(int argc, char** argv)`
> > > When I compile with cmake, there is only this error，Unable to find library without prompt
> > 
> > 
> > You have to link against the nvcaffeparser.lib: https://github.com/drostifrosti/TensorRT
> > > Hope to point out, the configuration of this has been four days, still did not succeed
> > 
> > 
> > I needed 2 weeks to port the whole library stack to Windows and compare the 2 versions of OpenPose, so keep going ;-)
> 
> Sorry to bother you again. I commented the source Openpose (according to your advice) and compiled it again. I found that I didn't have what you said lib（nvcaffeparser.lib），Below is my Tensorrt directory
> ![image](https://user-images.githubusercontent.com/48466610/127964698-38ced279-18fb-4596-849d-99c81e1b7495.png)
> this is CMakeLists.txt about tensorrt config, hope give me some advice,I'm not sure if my cmakelists.txt has a problem with the tensorrt modification or if the downloaded TensorRT is missing something(like you said nvcaffeparser.lib )
> ![image](https://user-images.githubusercontent.com/48466610/127965062-a163c59c-cde2-4251-9736-5b2345749b5c.png)

same error is this,
![image](https://user-images.githubusercontent.com/48466610/127965441-ecc5c4b5-654e-4ab2-9656-656b4b83fe70.png)

**Comment by drostifrosti** [comment]
nvcaffeparser.lib is not included in the Windows download (who knows why), that's why you have to build it yourself, as always with modifications for Windows found in my repo

**Comment by zhanghongyong123456** [comment]
> nvcaffeparser.lib is not included in the Windows download (who knows why), that's why you have to build it yourself, as always with modifications for Windows found in my repo

1. You mean that I need to build a TensorRT by myself instead of using the official Windows version. 
2. Source code compilation is based on your library（https://github.com/drostifrosti/TensorRT）, or need to download the corresponding CUDA version of TensorRT official TensorRT（https://github.com/NVIDIA/TensorRT） to compile，my computer configuration   RTX 2060 supper  CUDA 10.2 
3. Did you make any changes to the tensorRT source code to fit this project，

**Comment by drostifrosti** [comment]
1. yes, it suffices to build the nvcaffeparser.lib alone and put it in the already existing TensorRT install directory
2. my fork consists of some minor modifications but otherwise it's the same repo
3. yes, as I already mentioned

**Comment by zhanghongyong123456** [comment]
> 1. yes, it suffices to build the nvcaffeparser.lib alone and put it in the already existing TensorRT install directory
> 2. my fork consists of some minor modifications but otherwise it's the same repo
> 3. yes, as I already mentioned

Can I use your  repo（https://github.com/drostifrosti/TensorRT） to compile nvCaffeineparser.lib?The TensorRT I used is tensorrt-7.2.1.6-CU10.2. I wonder if it matches your repo,Whether I can compile directly, there is no version problem

**Comment by drostifrosti** [comment]
If you took a quick look in the VERSION file in my repo, you could see that I forked 7.2.1.6 and again yes, you can take my repo to compile the lib.

**Comment by zhanghongyong123456** [comment]
> If you took a quick look in the VERSION file in my repo, you could see that I forked 7.2.1.6 and again yes, you can take my repo to compile the lib.
Ok, thanks for your reply, my concern is that for 7.2.1.6, there are different CUDA versions (e.g. CUDA10.0  CUDA10.2  CUDA11.1), and suddenly I find Windows compilation too difficult

**Comment by zhanghongyong123456** [comment]
> > If you took a quick look in the VERSION file in my repo, you could see that I forked 7.2.1.6 and again yes, you can take my repo to compile the lib.
> > Ok, thanks for your reply, my concern is that for 7.2.1.6, there are different CUDA versions (e.g. CUDA10.0  CUDA10.2  CUDA11.1), and suddenly I find Windows compilation too difficult

sorry ，no cuda10.0，
![image](https://user-images.githubusercontent.com/48466610/127972272-f5a21a8e-8aeb-4970-a8d7-471d07a3336b.png)

**Comment by zhanghongyong123456** [comment]
> If you took a quick look in the VERSION file in my repo, you could see that I forked 7.2.1.6 and again yes, you can take my repo to compile the lib.

Hello, I would like to know how to independently compile the nvcaffeparser.lib file. I checked the official website and did not find the tutorial compiled by myself in Windows，Blogs don't have this information either，Hope to give some advice

**Comment by zhanghongyong123456** [comment]
> > If you took a quick look in the VERSION file in my repo, you could see that I forked 7.2.1.6 and again yes, you can take my repo to compile the lib.
> 
> Hello, I would like to know how to independently compile the nvcaffeparser.lib file. I checked the official website and did not find the tutorial compiled by myself in Windows，Blogs don't have this information either，Hope to give some advice

![image](https://user-images.githubusercontent.com/48466610/127978361-43bb47e0-8c8a-4569-84a5-2c09f3de7b57.png)

**Comment by zhanghongyong123456** [comment]
> > If you took a quick look in the VERSION file in my repo, you could see that I forked 7.2.1.6 and again yes, you can take my repo to compile the lib.
> 
> Hello, I would like to know how to independently compile the nvcaffeparser.lib file. I checked the official website and did not find the tutorial compiled by myself in Windows，Blogs don't have this information either，Hope to give some advice
Compile the results：
![image](https://user-images.githubusercontent.com/48466610/128024758-2524fd3c-4037-4f95-af34-2850855e06af.png)
Here's the code I commented out，
![image](https://user-images.githubusercontent.com/48466610/128025116-ccdd26ca-f6a8-4b1c-adb9-4c11f03de414.png)
![image](https://user-images.githubusercontent.com/48466610/128025162-b3d110ea-686a-4c91-bf56-0e92205eb51f.png)
What do I need to change here
![image](https://user-images.githubusercontent.com/48466610/128025436-d42e9bf6-92c4-40f2-8d4f-4a7e4b5bb195.png)

**Comment by drostifrosti** [comment]
> Hello, I would like to know how to independently compile the nvcaffeparser.lib file. I checked the official website and did not find the tutorial compiled by myself in Windows，Blogs don't have this information either，Hope to give some advice

You just build the project nvcaffeparser (I had to rebuild it so that VS regenerates the lib file)

For the undefined class problem try to `#include <fstream>` and `using namespace std;`

**Comment by chh7411898** [comment]
> ich exclude parts of his work, which I didn't need in my personal project)



> > want to compile under Windows, but I am not familiar with Cmake. Could you briefly explain the compile process and how to configure Cmake? Thank you，windows10.1 python 3.8 cuda 10.2 TensorRT 7.2.1.6 opencv 4.5.1 cmake GUI 3.19.2
> > thank you very much for your help
> 
> I got this problem at compile time ![31](https://user-images.githubusercontent.com/48466610/126941828-02ec2e0a-6a72-4981-b7b2-2c923c1275ed.png) When I remove the -d identifier ![32](https://user-images.githubusercontent.com/48466610/126941904-18d8f7e5-da8b-4cd0-8ec4-90a489622d4d.png) ![33](https://user-images.githubusercontent.com/48466610/126941931-c974c9ba-1b39-42c5-a12e-a0e19ee9a248.png)

hi  I also encountered this problem. How did you  solve it?
